# Generated by Django 4.1.5 on 2023-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='shortDesc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
