# Generated by Django 4.1.5 on 2023-03-12 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_doctormodel_shortdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='avatar',
            field=models.ImageField(default='doctor.png', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
