# Generated by Django 4.1.1 on 2023-01-29 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_salesdata_alter_countrydata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydata',
            name='dateNow',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydata',
            name='money',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
