# Generated by Django 4.1.1 on 2023-01-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_countrydata_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydata',
            name='author',
        ),
    ]
