# Generated by Django 4.1.1 on 2023-02-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_dashboarddata_delete_countrydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarddata',
            options={},
        ),
    ]
