# Generated by Django 4.1.1 on 2023-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_predictiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='diastolic_bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='glucose',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='systolic_bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
