# Generated by Django 4.1.1 on 2023-02-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_dashboarddata_diastolic_bp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictiondata',
            options={},
        ),
    ]
