# Generated by Django 4.1.1 on 2023-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_predictiondata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiondata',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='predictiondata',
            name='parentAgeDiabetes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='predictiondata',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='bmi',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='dpf',
            field=models.FloatField(blank=True),
        ),
    ]
