# Generated by Django 4.1.1 on 2023-02-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_predictiondata_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiondata',
            name='bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='dpf',
            field=models.FloatField(null=True),
        ),
    ]
