# Generated by Django 4.1.1 on 2023-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_predictiondata_bmi_alter_predictiondata_dpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiondata',
            name='dpf',
            field=models.FloatField(blank=True),
        ),
    ]
