# Generated by Django 4.1.1 on 2023-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_predictiondata_parentagediabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiondata',
            name='dpf',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
