# Generated by Django 4.1.1 on 2023-02-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_predictiondata_defaultparentagediabetes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiondata',
            name='defaultparentAgeDiabetes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='parentAgeDiabetes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
