# Generated by Django 4.1.1 on 2023-02-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_predictiondata_defaultparentagediabetes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictiondata',
            name='defaultparentAgeDiabetes',
        ),
        migrations.RemoveField(
            model_name='predictiondata',
            name='parentAgeDiabetes',
        ),
    ]
