# Generated by Django 4.1.1 on 2023-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_predictiondata_defaultparentagediabetes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiondata',
            name='dpf',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
