# Generated by Django 4.1.1 on 2023-02-11 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_profilemodel_firstname_profilemodel_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='default/blank-profile-picture-973460_960_720.jpg', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='firstName',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='lastName',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phoneNum',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=100, null=True),
        ),
    ]
