# Generated by Django 4.1.1 on 2023-02-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_profilemodel_address_alter_profilemodel_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='firstName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phoneNum',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=100),
        ),
    ]
