# Generated by Django 4.1.1 on 2023-02-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_profilemodel_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='diastolic_bp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='glucose',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='systolic_bp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
