# Generated by Django 4.1.5 on 2023-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_dashboarddata_diastolic_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='glucose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
