# Generated by Django 4.1.5 on 2023-02-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_dashboarddata_diastolic_bp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarddata',
            options={'ordering': ('-dateNow',)},
        ),
        migrations.AlterModelOptions(
            name='predictiondata',
            options={'ordering': ('-date',)},
        ),
    ]
