# Generated by Django 4.1.5 on 2023-02-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_dashboarddata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarddata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='predictiondata',
            options={},
        ),
    ]
