# Generated by Django 4.1.5 on 2023-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_dashboarddata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='diastolic_bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='glucose',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='systolic_bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
