# Generated by Django 4.1.5 on 2023-02-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_messagepanel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagepanel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='MessagePanel',
        ),
    ]
